on:
  push:
    paths-ignore:
      - 'workspaces/**'
      - 'mesh-demo/**'
jobs:
  deploy_to_clouds:
    runs-on: ubuntu-latest
    name: Deploying Kong Configuration
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v2.2.0
      with:
        node-version: "12"
    - name: Install DecK
      run: |
        curl -sL https://github.com/kong/deck/releases/download/v1.2.0/deck_1.2.0_linux_amd64.tar.gz -o deck.tar.gz
        tar -xf deck.tar.gz -C /tmp
        cp /tmp/deck /usr/local/bin/
    - name: Install Insomnia
      run: |
        curl -sL https://github.com/Kong/insomnia/releases/download/lib%402.4.0/inso-linux-2.4.0.tar.xz -o inso.tar.xz
        sudo tar -xf inso.tar.xz -C /tmp/
        cp /tmp/inso /usr/local/bin/
    - run: inso -w $GITHUB_WORKSPACE export spec blog -o blog.yaml --ci
      name: Export blog spec
    - name: Substitute secrets
      uses: bluwy/substitute-string-action@v1
      id: blog-yaml
      with:
        _input-file: blog.yaml
        OIDC_CLIENT_ID: ${{ secrets.OIDC_CLIENT_ID }}
        OIDC_CLIENT_SECRET: ${{ secrets.OIDC_CLIENT_SECRET }}
    - name: Output OAS to file
      run: echo "${{ steps.blog-yaml.outputs.result }}" > blog-new.yaml
    - name: Generate new gateway configuration
      run: inso generate config blog-new.yaml -o kong-new.yaml --tags gitops --ci
    - name: Backup existing configuration
      run: deck dump --headers Kong-Admin-Token:kong_admin --workspace default -o kong-default.yaml --select-tag gitops --tls-skip-verify
      env:
        DECK_KONG_ADDR: ${{ secrets.ADMIN_API_URL }}
    - name: Apply new configuration
      run: deck sync --headers Kong-Admin-Token:kong_admin --workspace default --select-tag gitops -s kong-new.yaml --tls-skip-verify
      env:
        DECK_KONG_ADDR: ${{ secrets.ADMIN_API_URL }}
    - name: Run API Tests
      run: |
        inso -w $GITHUB_WORKSPACE run test -e Development "Policy Guardrails" --ci --disableCertValidation
    - name: Back out changes on failure
      if: ${{ failure() }}
      run: deck sync --headers Kong-Admin-Token:kong_admin --workspace default -s kong-default.yaml --select-tag gitops --tls-skip-verify
      env:
        DECK_KONG_ADDR: ${{ secrets.ADMIN_API_URL }}
